name: cempulse
description: "A new Flutter project."
publish_to: 'none' # this is a private project, not published on pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # UI Essentials
  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2

  # Launcher & Splash
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

  # Charts & Gauges (modern + maintained)
  fl_chart: ^1.1.0
  syncfusion_flutter_charts: ^31.1.17
  syncfusion_flutter_gauges: ^31.1.17

  # Progress Indicators
  percent_indicator: ^4.2.3

  # IoT & Connectivity
  mqtt_client: ^10.11.1
  flutter_reactive_ble: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Cem-Pulse-Logo.PNG

flutter_icons:
  android: true
  ios: true
  image_path: assets/Cem-Pulse-Logo.PNG
